"""[1] bootstrap

Revision ID: c88aed86a2c6
Revises:
Create Date: 2017-05-07 01:59:44.368891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c88aed86a2c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['match_uuid'], ['match.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=False),
    sa.Column('match_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['match_uuid'], ['match.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('seed', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('low_value', sa.Integer(), nullable=True),
    sa.Column('high_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_uuid', postgresql.UUID(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['match_uuid'], ['match.uuid'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand')
    op.drop_table('card')
    op.drop_table('player')
    op.drop_table('deck')
    op.drop_table('match')
    # ### end Alembic commands ###
